apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdatabase
  namespace: gazellig-prod
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: postgresdatabase
  template:
    metadata:
      labels:
        name: postgresdatabase
    spec:
      containers:
      - name: postgresdatabase
        image: postgres
        ports:
        - name: postgresport
          containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: Geheim_101
        resources:
          requests:
            memory: "200Mi"
            cpu: "30m"
          limits:
            memory: "512Mi"
            cpu: "100m"
        volumeMounts:
        - name: storage
          mountPath: /var/lib/postgresql
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage

---

apiVersion: v1
kind: Service
metadata:
  name: postgresdatabase
  namespace: gazellig-prod
spec:
  selector:
    name: postgresdatabase
  ports:
  - name: postgresport
    protocol: TCP
    port: 5432

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
  namespace: gazellig-prod
spec:
  storageClassName: azurefile
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
