apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-bestellingen
  namespace: gazellig-prod
spec:
  selector:
    matchLabels:
      name: bff-bestellingen
  template:
    metadata:
      labels:
        name: bff-bestellingen
    spec:
      containers:
        - name: bff-bestellingen
          image: **/gazellig/microservice-bff-bestellingen:master-17
          env:
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USERNAME
            value: Kantilever
          - name: RABBITMQ_PASSWORD
            value: Kantilever
          - name: AUDITLOG_URL
            value: http://miffy-auditlog
          - name: AUDITLOG_PORT
            value: "2022"
          - name: DATASOURCE_URL
            value: postgresql://postgresdatabase:5432
          - name: DATASOURCE_NAME
            value: bffbestellingendb
          - name: DATASOURCE_USERNAME
            value: postgres
          - name: DATASOURCE_PASSWORD
            value: Geheim_101
          resources:
            requests:
              memory: "150Mi"
              cpu: "30m"
            limits:
              memory: "500Mi"
              cpu: "200m"
          ports:
            - containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 30
            failureThreshold: 10
            exec:
              command:
                - /bin/sh
                - -c
                - 'wget -O - 0.0.0.0:8080/actuator/health | grep -qF "{\"status\":\"UP\"}"'
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 30
            failureThreshold: 10
            exec:
              command:
                - /bin/sh
                - -c
                - 'wget -O - 0.0.0.0:8080/actuator/health | grep -qF "{\"status\":\"UP\"}"'
      #     volumeMounts:
      #       - name: storage-logs-gateway
      #         mountPath: /logs
      # volumes:
      #   - name: storage-logs-gateway
      #     persistentVolumeClaim:
      #       claimName: storage-logs-gateway

      imagePullSecrets:
        - name: **

---

apiVersion: v1
kind: Service
metadata:
  name: bff-bestellingen
  namespace: gazellig-prod
spec:
  selector:
    name: bff-bestellingen
  ports:
    - protocol: TCP
      port: 8080

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bff-bestellingen
  namespace: gazellig-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /gazellig-bff-bestellingen/prod(/|$)(.*)
            backend:
              serviceName: bff-bestellingen
              servicePort: 8080

# --- 

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: storage-logs-bff-bestellingen
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 256Mi
